---
abstract: 'parse tiled game maps from http://www.mapeditor.org'
author:
  - 'Ran Eilam <eilara@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-TMX-Parser
requires:
  Moose: 2.0204
  XML::Twig: 3.39
version: 0.91
